### ISSUE TITLE
Feedback (Variables) are not updated automatically

### ISSUE THREAD

**Issue by echalupka** [bitfocus/companion-module-roku-tv#7]
Module must be disabled/enabled to receive new feedback variables from TV.

**Comment by josephdadams** [comment]
Only the active app is polled for updated data. What other variables are you interested in getting on an interval?

**Comment by echalupka** [comment]
We have 10 instances of the module installed. I'd love to see $(Roku-Green Room:power-mode) updated every 30-60 seconds. Thank you!

**Comment by mmpwhit** [comment]
A power option reporting back would be great. I just wanted to confirm the behavior we are seeing. I setup the feedback to report back the active input. That way when the TV is on it reports back the information because the input is on. I have an issue because every day I have to go into the connections and hit edit and save before it will report the feedback. Is this a known issue?

**Comment by cpuguru07** [comment]
I am also experiencing this issue with multiple instances of this module.

**Comment by josephdadams** [comment]
I still need to update this module for the new companion API. I will see if I can address this whenever I have time to get to that.

**Comment by josephdadams** [comment]
I added a power state feedback
